######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 2 20:31:21 2016
######################################################################

QWT_INCLUDE      =
QWTPOLAR_INCLUDE =
QWT_LIB          =
QWTPOLAR_LIB     =

QT          += svg

TARGET       = polardemo

# Input
HEADERS += mainwindow.hpp pixmaps.hpp plot.hpp settingseditor.hpp
SOURCES += main.cpp mainwindow.cpp plot.cpp settingseditor.cpp

CONFIG         += qwt
CONFIG         += qwtpolar
INCLUDEPATH    += $(QWT_INCLUDE)
INCLUDEPATH    += $(QWTPOLAR_INCLUDE)
INCLUDEPATH    += ../src
LIBS           += $(QWT_LIB) -lqwt
LIBS           += $(QWTPOLAR_LIB) -lqwtpolar
LIBS           += -L../src -lngpt
QMAKE_CXXFLAGS += -std=c++11 -fPIC
